//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.DatabaseContent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int postID { get; set; }
        public string postCaption { get; set; }
        public string postImg { get; set; }
        public Nullable<int> posterID { get; set; }
        public string posterName { get; set; }
    
        public virtual User User { get; set; }
    }
}
